VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "ILocator"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Public Property Get Top() As Long
End Property

Public Property Get Left() As Long
End Property

Public Property Get Bottom() As Long
End Property

Public Property Get Right() As Long
End Property

Public Sub Locate(r As Range)
End Sub
